version: '3.7'
services:
  app: 
    build: ./backend
    container_name: backend
    volumes:
      - type: bind
        source: ./backend/migrations/versions
        target: /code/backend/migrations/versions
        volume:
          nocopy: true
      

    env_file:
      - .env
    ports:
      - "8008:8000"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0"

    restart: always
  
  pg_db:
    image:  postgres:13
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

    
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pg_db
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin


volumes: 
  data:
