version: '3.8'
services:
  app: 
    build: .
    container_name: film_assistant

    ports:
      - "8008:8000"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0"
  
  db:
    image:  postgres:13.3
    ports:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: employment_exchange