"""init

Revision ID: 7db5ec8181ac
Revises: 
Create Date: 2022-04-24 20:14:51.902281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db5ec8181ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('email')
    )
    op.create_table('films_selected',
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('name_film', sa.String(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('img_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_film')
    )
    op.create_table('search_film_history',
    sa.Column('id_search', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('name_film', sa.String(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('rating_start', sa.Float(), nullable=True),
    sa.Column('rating_end', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_search')
    )
    op.create_table('user_profile',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_table('users_authentication',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('generated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('auth_code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_table('film_history_by_search',
    sa.Column('id_search_film', sa.Integer(), nullable=True),
    sa.Column('name_film', sa.String(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('img_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_search_film'], ['search_film_history.id_search'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_history_by_search')
    op.drop_table('users_authentication')
    op.drop_table('user_profile')
    op.drop_table('search_film_history')
    op.drop_table('films_selected')
    op.drop_table('users')
    # ### end Alembic commands ###
